//! Testi dell'interfaccia in italiano e in inglese (UTF-16 con zero finale).

/// Tutti i testi mostrati all'utente.
#[allow(dead_code)]
pub struct Strings {
    pub cpu: &'static [u16],
    pub menu_interval: &'static [u16],
    pub interval_1s: &'static [u16],
    pub interval_2s: &'static [u16],
    pub interval_5s: &'static [u16],
    pub menu_power: &'static [u16],
    pub power_pause_display: &'static [u16],
    pub power_slow_saver: &'static [u16],
    pub power_ecoqos: &'static [u16],
    pub menu_autostart: &'static [u16],
    pub menu_show_icon: &'static [u16],
    pub menu_about: &'static [u16],
    pub menu_exit: &'static [u16],
    #[allow(dead_code)]
    pub about_body: &'static [u16],
    pub balloon_title: &'static [u16],
    pub balloon_first_run: &'static [u16],
    #[allow(dead_code)]
    pub balloon_already_running: &'static [u16],
    pub balloon_portable_readonly: &'static [u16],
    // M2
    pub ram: &'static [u16],
    pub net: &'static [u16],
    pub menu_active: &'static [u16],
    pub menu_icon: &'static [u16],
    pub menu_utility: &'static [u16],
    pub menu_sat_always: &'static [u16],
    pub menu_sat_ondemand: &'static [u16],
    pub menu_sat_off: &'static [u16],
    pub menu_net_sum: &'static [u16],
    pub menu_net_auto: &'static [u16],
    pub menu_net_bits: &'static [u16],
    // M3
    pub temp: &'static [u16],
    pub menu_temp_acpi: &'static [u16],
    pub menu_temp_gpu: &'static [u16],
    pub menu_temp_disk: &'static [u16],
    pub menu_cpu_per_core: &'static [u16],
    pub temp_fixed: &'static [u16],
    pub seconds_ago: &'static [u16],
    pub menu_icon_symbol: &'static [u16],
    pub menu_back: &'static [u16],
    pub menu_back_temp: &'static [u16],
    // Inspect Window ("Il Grande Passo")
    pub inspect_title: &'static [u16],
    pub inspect_tab_processes: &'static [u16],
    pub inspect_tab_sockets: &'static [u16],
    pub inspect_tab_services: &'static [u16],
    pub inspect_tab_settings: &'static [u16],
    pub inspect_tab_info: &'static [u16],
    pub inspect_col_name: &'static [u16],
    pub inspect_col_pid: &'static [u16],
    pub inspect_col_cpu: &'static [u16],
    pub inspect_col_ws: &'static [u16],
    pub inspect_col_priv: &'static [u16],
    pub inspect_col_threads: &'static [u16],
    pub inspect_col_assoc: &'static [u16],
    pub inspect_col_proto: &'static [u16],
    pub inspect_col_local: &'static [u16],
    pub inspect_col_remote: &'static [u16],
    pub inspect_col_state: &'static [u16],
    pub inspect_col_display: &'static [u16],
    pub inspect_btn_kill: &'static [u16],
    pub inspect_btn_close_conn: &'static [u16],
    pub inspect_btn_stop_svc: &'static [u16],
    pub inspect_btn_start_svc: &'static [u16],
    pub inspect_btn_refresh: &'static [u16],
    pub inspect_search_hint: &'static [u16],
    pub inspect_title_admin: &'static [u16],
    pub inspect_btn_restart_admin: &'static [u16],
    pub inspect_btn_taskmgr: &'static [u16],
    pub inspect_btn_group: &'static [u16],
    pub inspect_btn_settings: &'static [u16],
    pub menu_metrics_group: &'static [u16],
    pub menu_system_group: &'static [u16],
    pub menu_restart_admin: &'static [u16],
    pub menu_autostart_admin: &'static [u16],
    pub menu_check_updates: &'static [u16],
    pub inspect_btn_check_updates: &'static [u16],
    pub inspect_btn_download_update: &'static [u16],
}

pub static IT: Strings = Strings {
    cpu: wide!("CPU"),
    menu_interval: wide!("Aggiorna ogni"),
    interval_1s: wide!("1 secondo"),
    interval_2s: wide!("2 secondi"),
    interval_5s: wide!("5 secondi"),
    menu_power: wide!("Risparmio energia"),
    power_pause_display: wide!("Pausa a schermo spento"),
    power_slow_saver: wide!("Più lento col risparmio energia"),
    power_ecoqos: wide!("EcoQoS (core efficienti)"),
    menu_autostart: wide!("Avvia con Windows"),
    menu_show_icon: wide!("Mostra sempre l'icona…"),
    menu_about: wide!("Informazioni"),
    menu_exit: wide!("Esci"),
    about_body: wide!("Indicatore di sistema leggerissimo per Windows 11.\n\nLicenza: MIT OR Apache-2.0"),
    balloon_title: wide!("nextm"),
    balloon_first_run: wide!("nextm è nella tray. Clicca qui per tenerlo sempre visibile nella barra."),
    balloon_already_running: wide!("nextm è già attivo: è questa icona."),
    balloon_portable_readonly: wide!(
        "La cartella di nextm non è scrivibile: le impostazioni vengono salvate nel registro."
    ),
    ram: wide!("RAM"),
    net: wide!("Rete"),
    menu_active: wide!("Attiva"),
    menu_icon: wide!("Icona"),
    menu_utility: wide!("Utilità"),
    menu_sat_always: wide!("Core saturo: sempre"),
    menu_sat_ondemand: wide!("Core saturo: solo a richiesta"),
    menu_sat_off: wide!("Core saturo: spento"),
    menu_net_sum: wide!("Tutte le schede fisiche (somma)"),
    menu_net_auto: wide!("Automatica (scheda principale)"),
    menu_net_bits: wide!("bit/s"),
    temp: wide!("Temperature"),
    menu_temp_acpi: wide!("CPU / Scheda madre (ACPI)"),
    menu_temp_gpu: wide!("GPU"),
    menu_temp_disk: wide!("Disco / SSD (NVMe/SATA)"),
    menu_cpu_per_core: wide!("Dettaglio singoli core al passaggio del mouse"),
    temp_fixed: wide!("fissa"),
    seconds_ago: wide!("s fa"),
    menu_icon_symbol: wide!("Icona con simbolo"),
    menu_back: wide!("◄ Menu principale"),
    menu_back_temp: wide!("◄ Temperature"),
    inspect_title: wide!("nextm — Ispezione di Sistema"),
    inspect_tab_processes: wide!("Processi"),
    inspect_tab_sockets: wide!("Connessioni Rete"),
    inspect_tab_services: wide!("Servizi Windows"),
    inspect_tab_settings: wide!("Impostazioni"),
    inspect_tab_info: wide!("Info"),
    inspect_col_name: wide!("Nome Processo"),
    inspect_col_pid: wide!("PID"),
    inspect_col_cpu: wide!("CPU %"),
    inspect_col_ws: wide!("Memoria (WS)"),
    inspect_col_priv: wide!("Mem. Privata"),
    inspect_col_threads: wide!("Thread"),
    inspect_col_assoc: wide!("Servizi / Connessioni"),
    inspect_col_proto: wide!("Proto"),
    inspect_col_local: wide!("Indirizzo Locale"),
    inspect_col_remote: wide!("Indirizzo Remoto"),
    inspect_col_state: wide!("Stato"),
    inspect_col_display: wide!("Descrizione Servizio"),
    inspect_btn_kill: wide!("Termina Processo"),
    inspect_btn_close_conn: wide!("Chiudi Connessione"),
    inspect_btn_stop_svc: wide!("Arresta Servizio"),
    inspect_btn_start_svc: wide!("Avvia Servizio"),
    inspect_btn_refresh: wide!("Aggiorna"),
    inspect_search_hint: wide!("Cerca per nome, PID, porta, IP o servizio..."),
    inspect_title_admin: wide!("nextm — Ispezione di Sistema [Amministratore]"),
    inspect_btn_restart_admin: wide!("🛡️ Riavvia come Admin"),
    inspect_btn_taskmgr: wide!("Gestione Attività"),
    inspect_btn_group: wide!("Raggruppa"),
    inspect_btn_settings: wide!("⚙ Impostazioni ▾"),
    menu_metrics_group: wide!("Metriche nella tray"),
    menu_system_group: wide!("Sistema e avvio"),
    menu_restart_admin: wide!("🛡️ Esegui come Amministratore"),
    menu_autostart_admin: wide!("🛡️ Avvia come Amministratore all'accesso"),
    menu_check_updates: wide!("Controlla aggiornamenti…"),
    inspect_btn_check_updates: wide!("Controlla aggiornamenti"),
    inspect_btn_download_update: wide!("Scarica aggiornamento"),
};

pub static EN: Strings = Strings {
    cpu: wide!("CPU"),
    menu_interval: wide!("Update every"),
    interval_1s: wide!("1 second"),
    interval_2s: wide!("2 seconds"),
    interval_5s: wide!("5 seconds"),
    menu_power: wide!("Power saving"),
    power_pause_display: wide!("Pause while the screen is off"),
    power_slow_saver: wide!("Slower with Energy Saver"),
    power_ecoqos: wide!("EcoQoS (efficient cores)"),
    menu_autostart: wide!("Start with Windows"),
    menu_show_icon: wide!("Always show the icon…"),
    menu_about: wide!("About"),
    menu_exit: wide!("Exit"),
    about_body: wide!("Ultra-light system indicator for Windows 11.\n\nLicense: MIT OR Apache-2.0"),
    balloon_title: wide!("nextm"),
    balloon_first_run: wide!("nextm is in the notification area. Click here to keep it always visible on the taskbar."),
    balloon_already_running: wide!("nextm is already running: it's this icon."),
    balloon_portable_readonly: wide!("nextm's folder is not writable: settings are saved in the registry."),
    ram: wide!("RAM"),
    net: wide!("Network"),
    menu_active: wide!("Active"),
    menu_icon: wide!("Icon"),
    menu_utility: wide!("Utility"),
    menu_sat_always: wide!("Saturated core: always"),
    menu_sat_ondemand: wide!("Saturated core: on demand"),
    menu_sat_off: wide!("Saturated core: off"),
    menu_net_sum: wide!("All physical interfaces (sum)"),
    menu_net_auto: wide!("Automatic (primary interface)"),
    menu_net_bits: wide!("bit/s"),
    temp: wide!("Temperatures"),
    menu_temp_acpi: wide!("CPU / Motherboard (ACPI)"),
    menu_temp_gpu: wide!("GPU"),
    menu_temp_disk: wide!("Disk / SSD (NVMe/SATA)"),
    menu_cpu_per_core: wide!("Per-core details on hover"),
    temp_fixed: wide!("fixed"),
    seconds_ago: wide!("s ago"),
    menu_icon_symbol: wide!("Icon with symbol"),
    menu_back: wide!("◄ Main menu"),
    menu_back_temp: wide!("◄ Temperatures"),
    inspect_title: wide!("nextm — System Inspection"),
    inspect_tab_processes: wide!("Processes"),
    inspect_tab_sockets: wide!("Network Sockets"),
    inspect_tab_services: wide!("Windows Services"),
    inspect_tab_settings: wide!("Settings"),
    inspect_tab_info: wide!("Info"),
    inspect_col_name: wide!("Process Name"),
    inspect_col_pid: wide!("PID"),
    inspect_col_cpu: wide!("CPU %"),
    inspect_col_ws: wide!("Memory (WS)"),
    inspect_col_priv: wide!("Private Mem"),
    inspect_col_threads: wide!("Threads"),
    inspect_col_assoc: wide!("Services / Sockets"),
    inspect_col_proto: wide!("Proto"),
    inspect_col_local: wide!("Local Address"),
    inspect_col_remote: wide!("Remote Address"),
    inspect_col_state: wide!("State"),
    inspect_col_display: wide!("Service Description"),
    inspect_btn_kill: wide!("Kill Process"),
    inspect_btn_close_conn: wide!("Close Connection"),
    inspect_btn_stop_svc: wide!("Stop Service"),
    inspect_btn_start_svc: wide!("Start Service"),
    inspect_btn_refresh: wide!("Refresh"),
    inspect_search_hint: wide!("Search by name, PID, port, IP or service..."),
    inspect_title_admin: wide!("nextm — System Inspection [Administrator]"),
    inspect_btn_restart_admin: wide!("🛡️ Restart as Admin"),
    inspect_btn_taskmgr: wide!("Task Manager"),
    inspect_btn_group: wide!("Group"),
    inspect_btn_settings: wide!("⚙ Settings ▾"),
    menu_metrics_group: wide!("Tray metrics"),
    menu_system_group: wide!("System and autostart"),
    menu_restart_admin: wide!("🛡️ Run as Administrator"),
    menu_autostart_admin: wide!("🛡️ Start as Administrator on logon"),
    menu_check_updates: wide!("Check for updates…"),
    inspect_btn_check_updates: wide!("Check for updates"),
    inspect_btn_download_update: wide!("Download update"),
};

/// Testi per una lingua dell'interfaccia (LANGID di Windows): italiano o, altrimenti, inglese.
pub fn for_langid(langid: u16) -> &'static Strings {
    const LANG_ITALIAN: u16 = 0x10;
    if langid & 0x3FF == LANG_ITALIAN { &IT } else { &EN }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn italian_variants_select_italian() {
        assert!(core::ptr::eq(for_langid(0x0410), &IT));
        assert!(core::ptr::eq(for_langid(0x0810), &IT));
    }

    #[test]
    fn other_languages_select_english() {
        assert!(core::ptr::eq(for_langid(0x0409), &EN));
        assert!(core::ptr::eq(for_langid(0x0407), &EN));
    }

    #[test]
    fn every_string_is_terminated() {
        for s in [&IT, &EN] {
            for w in [
                s.cpu,
                s.menu_interval,
                s.interval_1s,
                s.menu_power,
                s.power_slow_saver,
                s.menu_show_icon,
                s.about_body,
                s.balloon_first_run,
                s.balloon_portable_readonly,
                s.ram,
                s.net,
                s.menu_active,
                s.menu_icon,
                s.menu_utility,
                s.menu_sat_always,
                s.menu_sat_ondemand,
                s.menu_sat_off,
                s.menu_net_sum,
                s.menu_net_auto,
                s.menu_net_bits,
                s.temp,
                s.menu_temp_acpi,
                s.menu_temp_gpu,
                s.menu_temp_disk,
                s.menu_cpu_per_core,
                s.temp_fixed,
                s.seconds_ago,
                s.menu_icon_symbol,
                s.menu_back,
                s.menu_back_temp,
                s.inspect_title,
                s.inspect_tab_processes,
                s.inspect_tab_sockets,
                s.inspect_tab_services,
                s.inspect_tab_info,
                s.inspect_col_name,
                s.inspect_col_pid,
                s.inspect_col_cpu,
                s.inspect_col_ws,
                s.inspect_col_priv,
                s.inspect_col_threads,
                s.inspect_col_assoc,
                s.inspect_col_proto,
                s.inspect_col_local,
                s.inspect_col_remote,
                s.inspect_col_state,
                s.inspect_col_display,
                s.inspect_btn_kill,
                s.inspect_btn_close_conn,
                s.inspect_btn_stop_svc,
                s.inspect_btn_start_svc,
                s.inspect_btn_refresh,
                s.inspect_search_hint,
                s.inspect_title_admin,
                s.inspect_btn_restart_admin,
                s.inspect_btn_taskmgr,
                s.inspect_btn_group,
                s.inspect_btn_settings,
                s.menu_metrics_group,
                s.menu_system_group,
                s.menu_restart_admin,
                s.menu_autostart_admin,
            ] {
                assert_eq!(w.last(), Some(&0));
            }
        }
    }

    #[test]
    fn balloon_texts_fit_windows_limits() {
        // szInfo ha 256 unità, szInfoTitle 64 (zero finale compreso).
        for s in [&IT, &EN] {
            for w in [s.balloon_first_run, s.balloon_already_running, s.balloon_portable_readonly] {
                assert!(w.len() <= 256);
            }
            assert!(s.balloon_title.len() <= 64);
        }
    }
}
